[package]
name = "yume-pdq"
version = "0.1.2"
edition = "2024"
authors = ["Yumechi <yume@yumechi.jp>"]
description = "An optimized implementation of the PDQ hash function for high-throughput screening."
license = "Apache-2.0"
repository = "https://github.com/eternal-flame-AD/yume-pdq"
build = "build.rs"
exclude= [
    "test-data/*",
    ".vscode/*",
    "bench-plot/*",
]

[dependencies]
generic-array = "1.2"
num-traits = { version = "0.2", default-features = false }
rug = { version = "1.27", optional = true }
derive_more = { version = "2", features = ["add", "add_assign", "mul", "mul_assign", "not"], optional = true }
clap = { version = "4.5", features = ["derive"], optional = true }
rand = { version = "0.9", optional = true, default-features = false, features = ["small_rng"] }
core_affinity = { version = "0.8", optional = true }

[build-dependencies]
derive_more = { version = "2", features = ["add", "add_assign", "mul_assign"] }
rug = "1.27"
vergen = { version = "9", features = ["build", "cargo"] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
image = "0.25"
pdqhash = "0.1.1"
rand = "0.9"
rayon = "1.10"
rug = "1.27"

[[bench]]
name = "pdq"
harness = false

[profile.release]
lto = true

[features]
std = []
avx512 = []
reference-rug = ["std", "dep:rug", "dep:derive_more"]
unstable = []
lut-utils = []
cli = ["std", "dep:clap", "dep:rand", "lut-utils"]
hpc = ["std", "dep:core_affinity"]

[[bin]]
name = "yume-pdq"
path = "src/main.rs"
required-features = ["cli"]
