[package]
name = "yume-pdq-recall-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
yume-pdq = { path = "../../", features = ["std"] }

[build-dependencies]
cc = "1.2"

[features]
avx512 = ["yume-pdq/avx512"]