[workspace]
authors = ["eternal-flame-AD <yume@yumechi.jp>"]
channels = ["conda-forge"]
name = "step_by_step"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r-tidyverse = ">=2.0.0,<3"
r-cowplot = ">=1.1.3,<2"
r-patchwork = ">=1.3.0,<2"
r-gridextra = ">=2.3,<3"
r-pixmap = ">=0.4_13,<0.5"
