
name: Build macOS Distributable (evaluation only)

on:
    push:

jobs:
    build:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v4

        - name: Install nightly toolchain and Apple target
          uses: dtolnay/rust-toolchain@nightly
          with:
            components: rust-src
            targets: x86_64-apple-darwin

        - name: Build
          run: |
            mkdir -p ci-release
            # portable simd neon
            RUSTFLAGS="-Ctarget-feature=+neon" \
              cargo build --release \
              --bin yume-pdq \
              --features "cli portable-simd-fma"
            RUSTFLAGS="-Ctarget-feature=+neon -Cdebug-assertions=yes" \
              cargo test --release \
              --features "cli portable-simd-fma" -- --nocapture
            cp target/release/yume-pdq ci-release/yume-pdq-macos-evaluation-portable-simd-neon

            # scalar
            cargo build --release \
              --bin yume-pdq \
              --features "cli"
            RUSTFLAGS="-Cdebug-assertions=yes" \
              cargo test --release \
              --features "cli" -- --nocapture
            cp target/release/yume-pdq ci-release/yume-pdq-macos-evaluation-scalar


        - name: Publish Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: artifacts-macos
            path: ci-release/*
            retention-days: 14
